### ISSUE TITLE
[Roadmap] Refactor Roadmap

### ISSUE THREAD

**Issue by YaoJiayi** [LMCache/LMCache#287]
This is the roadmap for the new version of LMCache.

- [x] A preliminary version (local cpu + local disk) (#251 )
- [x] Support zero copy store/retrieve with optimized kernels (#289 , #293 ) 
- [x] Integration with vllm
- [ ] Support prefetch/retrieve from vllm scheduler/ochestrator?
- [ ] Support more fine-grained pipelining (e.g., layer-wise pipelining)
- [ ] Flush in original features
- [ ] Testing & Bug fixing & Performance tuning
- [ ] Stress testing (see how long the entire system can run)
